version: '3'
services:
  flask:
    image: wardpearce/paycord
    restart: unless-stopped
    ports:
      - "56733:80"
    environment:
      DISCORD_CLIENT_ID: "..."
      DISCORD_CLIENT_SECRET: "..."
      DISCORD_BOT_TOKEN: "..."
      DISCORD_GUILD_ID: "..."
      ROOT_DISCORD_IDS: "...,..."
      STRIPE_WEBHOOK_SECRET: "..."
      STRIPE_API_KEY: "..."
      LOGO_URL: "https://i.imgur.com/d5SBQ6v.png"
      PAGE_NAME: "Paycord"
      MONGO_IP: "mongodb"
      
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
