version: '3'
services:
  flask:
    image: wardpearce/paycord
    container_name: paycord_flask
    restart: unless-stopped
    ports:
      - "56733:80"
    environment:
      CURRENCY: "USD"

      PAGE_NAME: "Paycord"

      LOGO_URL: "https://i.imgur.com/d5SBQ6v.png"

      SUBSCRIPTION_RECURRENCE: "month"
      SUBSCRIPTION_INTERVAL: 1

      MONTHLY_GOAL: 0.0
      MONTHLY_GOAL_PARAGRAPH: "The goal below indicates how much our services cost a month to run.\nYou can help support our service by purchasing one of the packages below."

      THIRD_PARTY_MODULES: "paycord.built_ins.discord"  # coma sep

      MONGO_IP: "mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "paycord"

      DISCORD_API_URL: "https://discord.com/api"
      DISCORD_BOT_TOKEN: ""
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      DISCORD_GUILD_ID: ""
      DISCORD_WEBHOOK: "" # Leave blank to disable

      ROOT_DISCORD_IDS: "" # Comma sep

      STRIPE_WEBHOOK_SECRET: ""
      STRIPE_API_KEY: ""

      MESSAGE_ON_COMPLETE: "Thank you {username} for subscribing to {name} for {currency_symbol}{price}"
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: paycord_mongo
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
